// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/subscription/can_update_note.proto

package subscription_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanUpdateNoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target of a note indicates what type of LinkedIn profile this note belongs to.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// The vanity name of the LinkedIn profile, as it appears in its LinkedIn profile URL.
	PublicIdentifier string `protobuf:"bytes,2,opt,name=public_identifier,json=publicIdentifier,proto3" json:"public_identifier,omitempty"`
	// The id of the note's author.
	AuthorId string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Only return the remaining number of edits, without counting this request as an edit.
	ReadOnly      bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanUpdateNoteRequest) Reset() {
	*x = CanUpdateNoteRequest{}
	mi := &file_proto_subscription_can_update_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanUpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUpdateNoteRequest) ProtoMessage() {}

func (x *CanUpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_can_update_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*CanUpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_can_update_note_proto_rawDescGZIP(), []int{0}
}

func (x *CanUpdateNoteRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CanUpdateNoteRequest) GetPublicIdentifier() string {
	if x != nil {
		return x.PublicIdentifier
	}
	return ""
}

func (x *CanUpdateNoteRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CanUpdateNoteRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CanUpdateNoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of remaining edits the user can still perform.
	RemainingEdits int32 `protobuf:"varint,1,opt,name=remaining_edits,json=remainingEdits,proto3" json:"remaining_edits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CanUpdateNoteResponse) Reset() {
	*x = CanUpdateNoteResponse{}
	mi := &file_proto_subscription_can_update_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanUpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUpdateNoteResponse) ProtoMessage() {}

func (x *CanUpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_can_update_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*CanUpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_can_update_note_proto_rawDescGZIP(), []int{1}
}

func (x *CanUpdateNoteResponse) GetRemainingEdits() int32 {
	if x != nil {
		return x.RemainingEdits
	}
	return 0
}

var File_proto_subscription_can_update_note_proto protoreflect.FileDescriptor

var file_proto_subscription_can_update_note_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x61, 0x6e, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x14, 0x43, 0x61, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79,
	0x22, 0x40, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x64, 0x69,
	0x74, 0x73, 0x32, 0x6b, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x6f, 0x74, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x27, 0x5a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_subscription_can_update_note_proto_rawDescOnce sync.Once
	file_proto_subscription_can_update_note_proto_rawDescData []byte
)

func file_proto_subscription_can_update_note_proto_rawDescGZIP() []byte {
	file_proto_subscription_can_update_note_proto_rawDescOnce.Do(func() {
		file_proto_subscription_can_update_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_can_update_note_proto_rawDesc), len(file_proto_subscription_can_update_note_proto_rawDesc)))
	})
	return file_proto_subscription_can_update_note_proto_rawDescData
}

var file_proto_subscription_can_update_note_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_subscription_can_update_note_proto_goTypes = []any{
	(*CanUpdateNoteRequest)(nil),  // 0: subscription.CanUpdateNoteRequest
	(*CanUpdateNoteResponse)(nil), // 1: subscription.CanUpdateNoteResponse
}
var file_proto_subscription_can_update_note_proto_depIdxs = []int32{
	0, // 0: subscription.CanUpdateNote.CanUpdateNote:input_type -> subscription.CanUpdateNoteRequest
	1, // 1: subscription.CanUpdateNote.CanUpdateNote:output_type -> subscription.CanUpdateNoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_subscription_can_update_note_proto_init() }
func file_proto_subscription_can_update_note_proto_init() {
	if File_proto_subscription_can_update_note_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_can_update_note_proto_rawDesc), len(file_proto_subscription_can_update_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_can_update_note_proto_goTypes,
		DependencyIndexes: file_proto_subscription_can_update_note_proto_depIdxs,
		MessageInfos:      file_proto_subscription_can_update_note_proto_msgTypes,
	}.Build()
	File_proto_subscription_can_update_note_proto = out.File
	file_proto_subscription_can_update_note_proto_goTypes = nil
	file_proto_subscription_can_update_note_proto_depIdxs = nil
}
