// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/search/create_team_meta.proto

package search_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateTeamMeta_CreateTeamMeta_FullMethodName = "/search.CreateTeamMeta/CreateTeamMeta"
)

// CreateTeamMetaClient is the client API for CreateTeamMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateTeamMetaClient interface {
	// Create a team meta.
	CreateTeamMeta(ctx context.Context, in *CreateTeamMetaRequest, opts ...grpc.CallOption) (*CreateTeamMetaResponse, error)
}

type createTeamMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateTeamMetaClient(cc grpc.ClientConnInterface) CreateTeamMetaClient {
	return &createTeamMetaClient{cc}
}

func (c *createTeamMetaClient) CreateTeamMeta(ctx context.Context, in *CreateTeamMetaRequest, opts ...grpc.CallOption) (*CreateTeamMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamMetaResponse)
	err := c.cc.Invoke(ctx, CreateTeamMeta_CreateTeamMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateTeamMetaServer is the server API for CreateTeamMeta service.
// All implementations must embed UnimplementedCreateTeamMetaServer
// for forward compatibility.
type CreateTeamMetaServer interface {
	// Create a team meta.
	CreateTeamMeta(context.Context, *CreateTeamMetaRequest) (*CreateTeamMetaResponse, error)
	mustEmbedUnimplementedCreateTeamMetaServer()
}

// UnimplementedCreateTeamMetaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateTeamMetaServer struct{}

func (UnimplementedCreateTeamMetaServer) CreateTeamMeta(context.Context, *CreateTeamMetaRequest) (*CreateTeamMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeamMeta not implemented")
}
func (UnimplementedCreateTeamMetaServer) mustEmbedUnimplementedCreateTeamMetaServer() {}
func (UnimplementedCreateTeamMetaServer) testEmbeddedByValue()                        {}

// UnsafeCreateTeamMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateTeamMetaServer will
// result in compilation errors.
type UnsafeCreateTeamMetaServer interface {
	mustEmbedUnimplementedCreateTeamMetaServer()
}

func RegisterCreateTeamMetaServer(s grpc.ServiceRegistrar, srv CreateTeamMetaServer) {
	// If the following call pancis, it indicates UnimplementedCreateTeamMetaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateTeamMeta_ServiceDesc, srv)
}

func _CreateTeamMeta_CreateTeamMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateTeamMetaServer).CreateTeamMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateTeamMeta_CreateTeamMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateTeamMetaServer).CreateTeamMeta(ctx, req.(*CreateTeamMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateTeamMeta_ServiceDesc is the grpc.ServiceDesc for CreateTeamMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateTeamMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.CreateTeamMeta",
	HandlerType: (*CreateTeamMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeamMeta",
			Handler:    _CreateTeamMeta_CreateTeamMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search/create_team_meta.proto",
}
