// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/search/delete_team_meta.proto

package search_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeleteTeamMeta_DeleteTeamMeta_FullMethodName = "/search.DeleteTeamMeta/DeleteTeamMeta"
)

// DeleteTeamMetaClient is the client API for DeleteTeamMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeleteTeamMetaClient interface {
	// Delete a team meta.
	DeleteTeamMeta(ctx context.Context, in *DeleteTeamMetaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type deleteTeamMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewDeleteTeamMetaClient(cc grpc.ClientConnInterface) DeleteTeamMetaClient {
	return &deleteTeamMetaClient{cc}
}

func (c *deleteTeamMetaClient) DeleteTeamMeta(ctx context.Context, in *DeleteTeamMetaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeleteTeamMeta_DeleteTeamMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteTeamMetaServer is the server API for DeleteTeamMeta service.
// All implementations must embed UnimplementedDeleteTeamMetaServer
// for forward compatibility.
type DeleteTeamMetaServer interface {
	// Delete a team meta.
	DeleteTeamMeta(context.Context, *DeleteTeamMetaRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDeleteTeamMetaServer()
}

// UnimplementedDeleteTeamMetaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeleteTeamMetaServer struct{}

func (UnimplementedDeleteTeamMetaServer) DeleteTeamMeta(context.Context, *DeleteTeamMetaRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeamMeta not implemented")
}
func (UnimplementedDeleteTeamMetaServer) mustEmbedUnimplementedDeleteTeamMetaServer() {}
func (UnimplementedDeleteTeamMetaServer) testEmbeddedByValue()                        {}

// UnsafeDeleteTeamMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeleteTeamMetaServer will
// result in compilation errors.
type UnsafeDeleteTeamMetaServer interface {
	mustEmbedUnimplementedDeleteTeamMetaServer()
}

func RegisterDeleteTeamMetaServer(s grpc.ServiceRegistrar, srv DeleteTeamMetaServer) {
	// If the following call pancis, it indicates UnimplementedDeleteTeamMetaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeleteTeamMeta_ServiceDesc, srv)
}

func _DeleteTeamMeta_DeleteTeamMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeleteTeamMetaServer).DeleteTeamMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeleteTeamMeta_DeleteTeamMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeleteTeamMetaServer).DeleteTeamMeta(ctx, req.(*DeleteTeamMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeleteTeamMeta_ServiceDesc is the grpc.ServiceDesc for DeleteTeamMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeleteTeamMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.DeleteTeamMeta",
	HandlerType: (*DeleteTeamMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteTeamMeta",
			Handler:    _DeleteTeamMeta_DeleteTeamMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search/delete_team_meta.proto",
}
