// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/search/upsert_message.proto

package search_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpsertMessage_UpsertMessage_FullMethodName = "/search.UpsertMessage/UpsertMessage"
)

// UpsertMessageClient is the client API for UpsertMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpsertMessageClient interface {
	// Upsert a message.
	UpsertMessage(ctx context.Context, in *UpsertMessageRequest, opts ...grpc.CallOption) (*UpsertMessageResponse, error)
}

type upsertMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewUpsertMessageClient(cc grpc.ClientConnInterface) UpsertMessageClient {
	return &upsertMessageClient{cc}
}

func (c *upsertMessageClient) UpsertMessage(ctx context.Context, in *UpsertMessageRequest, opts ...grpc.CallOption) (*UpsertMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMessageResponse)
	err := c.cc.Invoke(ctx, UpsertMessage_UpsertMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpsertMessageServer is the server API for UpsertMessage service.
// All implementations must embed UnimplementedUpsertMessageServer
// for forward compatibility.
type UpsertMessageServer interface {
	// Upsert a message.
	UpsertMessage(context.Context, *UpsertMessageRequest) (*UpsertMessageResponse, error)
	mustEmbedUnimplementedUpsertMessageServer()
}

// UnimplementedUpsertMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpsertMessageServer struct{}

func (UnimplementedUpsertMessageServer) UpsertMessage(context.Context, *UpsertMessageRequest) (*UpsertMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMessage not implemented")
}
func (UnimplementedUpsertMessageServer) mustEmbedUnimplementedUpsertMessageServer() {}
func (UnimplementedUpsertMessageServer) testEmbeddedByValue()                       {}

// UnsafeUpsertMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpsertMessageServer will
// result in compilation errors.
type UnsafeUpsertMessageServer interface {
	mustEmbedUnimplementedUpsertMessageServer()
}

func RegisterUpsertMessageServer(s grpc.ServiceRegistrar, srv UpsertMessageServer) {
	// If the following call pancis, it indicates UnimplementedUpsertMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpsertMessage_ServiceDesc, srv)
}

func _UpsertMessage_UpsertMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsertMessageServer).UpsertMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsertMessage_UpsertMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsertMessageServer).UpsertMessage(ctx, req.(*UpsertMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpsertMessage_ServiceDesc is the grpc.ServiceDesc for UpsertMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpsertMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.UpsertMessage",
	HandlerType: (*UpsertMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertMessage",
			Handler:    _UpsertMessage_UpsertMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search/upsert_message.proto",
}
