// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: proto/discussions/get_discussion_read_status.proto

package discussions_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiscussionReadStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The target of a note indicates what type of LinkedIn profile this message belongs to.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// The vanity name of the LinkedIn profile, as it appears in its LinkedIn profile URL.
	PublicIdentifier string `protobuf:"bytes,2,opt,name=public_identifier,json=publicIdentifier,proto3" json:"public_identifier,omitempty"`
	// The ID of the team.
	TeamId string `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the user.
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetDiscussionReadStatusRequest) Reset() {
	*x = GetDiscussionReadStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_discussions_get_discussion_read_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiscussionReadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscussionReadStatusRequest) ProtoMessage() {}

func (x *GetDiscussionReadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discussions_get_discussion_read_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscussionReadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDiscussionReadStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_discussions_get_discussion_read_status_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiscussionReadStatusRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetDiscussionReadStatusRequest) GetPublicIdentifier() string {
	if x != nil {
		return x.PublicIdentifier
	}
	return ""
}

func (x *GetDiscussionReadStatusRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GetDiscussionReadStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_discussions_get_discussion_read_status_proto protoreflect.FileDescriptor

var file_proto_discussions_get_discussion_read_status_proto_rawDesc = []byte{
	0x0a, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x97, 0x01, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x2b, 0x0a, 0x11,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x86, 0x01, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x6b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2b, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69,
	0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f,
	0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x64, 0x69, 0x73,
	0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_discussions_get_discussion_read_status_proto_rawDescOnce sync.Once
	file_proto_discussions_get_discussion_read_status_proto_rawDescData = file_proto_discussions_get_discussion_read_status_proto_rawDesc
)

func file_proto_discussions_get_discussion_read_status_proto_rawDescGZIP() []byte {
	file_proto_discussions_get_discussion_read_status_proto_rawDescOnce.Do(func() {
		file_proto_discussions_get_discussion_read_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_discussions_get_discussion_read_status_proto_rawDescData)
	})
	return file_proto_discussions_get_discussion_read_status_proto_rawDescData
}

var file_proto_discussions_get_discussion_read_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_discussions_get_discussion_read_status_proto_goTypes = []any{
	(*GetDiscussionReadStatusRequest)(nil), // 0: discussions.GetDiscussionReadStatusRequest
	(*DiscussionReadStatus)(nil),           // 1: discussions.DiscussionReadStatus
}
var file_proto_discussions_get_discussion_read_status_proto_depIdxs = []int32{
	0, // 0: discussions.GetDiscussionReadStatus.GetDiscussionReadStatus:input_type -> discussions.GetDiscussionReadStatusRequest
	1, // 1: discussions.GetDiscussionReadStatus.GetDiscussionReadStatus:output_type -> discussions.DiscussionReadStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_discussions_get_discussion_read_status_proto_init() }
func file_proto_discussions_get_discussion_read_status_proto_init() {
	if File_proto_discussions_get_discussion_read_status_proto != nil {
		return
	}
	file_proto_discussions_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_discussions_get_discussion_read_status_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetDiscussionReadStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_discussions_get_discussion_read_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_discussions_get_discussion_read_status_proto_goTypes,
		DependencyIndexes: file_proto_discussions_get_discussion_read_status_proto_depIdxs,
		MessageInfos:      file_proto_discussions_get_discussion_read_status_proto_msgTypes,
	}.Build()
	File_proto_discussions_get_discussion_read_status_proto = out.File
	file_proto_discussions_get_discussion_read_status_proto_rawDesc = nil
	file_proto_discussions_get_discussion_read_status_proto_goTypes = nil
	file_proto_discussions_get_discussion_read_status_proto_depIdxs = nil
}
