// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.4
// source: proto/discussions/get_all_messages.proto

package discussions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetAllMessages_GetAllMessages_FullMethodName = "/discussions.GetAllMessages/GetAllMessages"
)

// GetAllMessagesClient is the client API for GetAllMessages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetAllMessagesClient interface {
	// Retrieves a Message.
	GetAllMessages(ctx context.Context, in *GetAllMessagesRequest, opts ...grpc.CallOption) (*GetAllMessagesResponse, error)
}

type getAllMessagesClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAllMessagesClient(cc grpc.ClientConnInterface) GetAllMessagesClient {
	return &getAllMessagesClient{cc}
}

func (c *getAllMessagesClient) GetAllMessages(ctx context.Context, in *GetAllMessagesRequest, opts ...grpc.CallOption) (*GetAllMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMessagesResponse)
	err := c.cc.Invoke(ctx, GetAllMessages_GetAllMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAllMessagesServer is the server API for GetAllMessages service.
// All implementations must embed UnimplementedGetAllMessagesServer
// for forward compatibility.
type GetAllMessagesServer interface {
	// Retrieves a Message.
	GetAllMessages(context.Context, *GetAllMessagesRequest) (*GetAllMessagesResponse, error)
	mustEmbedUnimplementedGetAllMessagesServer()
}

// UnimplementedGetAllMessagesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetAllMessagesServer struct{}

func (UnimplementedGetAllMessagesServer) GetAllMessages(context.Context, *GetAllMessagesRequest) (*GetAllMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMessages not implemented")
}
func (UnimplementedGetAllMessagesServer) mustEmbedUnimplementedGetAllMessagesServer() {}
func (UnimplementedGetAllMessagesServer) testEmbeddedByValue()                        {}

// UnsafeGetAllMessagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetAllMessagesServer will
// result in compilation errors.
type UnsafeGetAllMessagesServer interface {
	mustEmbedUnimplementedGetAllMessagesServer()
}

func RegisterGetAllMessagesServer(s grpc.ServiceRegistrar, srv GetAllMessagesServer) {
	// If the following call pancis, it indicates UnimplementedGetAllMessagesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetAllMessages_ServiceDesc, srv)
}

func _GetAllMessages_GetAllMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAllMessagesServer).GetAllMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetAllMessages_GetAllMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAllMessagesServer).GetAllMessages(ctx, req.(*GetAllMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetAllMessages_ServiceDesc is the grpc.ServiceDesc for GetAllMessages service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetAllMessages_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discussions.GetAllMessages",
	HandlerType: (*GetAllMessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllMessages",
			Handler:    _GetAllMessages_GetAllMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discussions/get_all_messages.proto",
}
