// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/discussions/get_all_discussions.proto

package discussions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetAllDiscussions_GetAllDiscussions_FullMethodName = "/discussions.GetAllDiscussions/GetAllDiscussions"
)

// GetAllDiscussionsClient is the client API for GetAllDiscussions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetAllDiscussionsClient interface {
	// Retrieves a Discussion.
	GetAllDiscussions(ctx context.Context, in *GetAllDiscussionsRequest, opts ...grpc.CallOption) (*GetAllDiscussionsResponse, error)
}

type getAllDiscussionsClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAllDiscussionsClient(cc grpc.ClientConnInterface) GetAllDiscussionsClient {
	return &getAllDiscussionsClient{cc}
}

func (c *getAllDiscussionsClient) GetAllDiscussions(ctx context.Context, in *GetAllDiscussionsRequest, opts ...grpc.CallOption) (*GetAllDiscussionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllDiscussionsResponse)
	err := c.cc.Invoke(ctx, GetAllDiscussions_GetAllDiscussions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAllDiscussionsServer is the server API for GetAllDiscussions service.
// All implementations must embed UnimplementedGetAllDiscussionsServer
// for forward compatibility.
type GetAllDiscussionsServer interface {
	// Retrieves a Discussion.
	GetAllDiscussions(context.Context, *GetAllDiscussionsRequest) (*GetAllDiscussionsResponse, error)
	mustEmbedUnimplementedGetAllDiscussionsServer()
}

// UnimplementedGetAllDiscussionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetAllDiscussionsServer struct{}

func (UnimplementedGetAllDiscussionsServer) GetAllDiscussions(context.Context, *GetAllDiscussionsRequest) (*GetAllDiscussionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDiscussions not implemented")
}
func (UnimplementedGetAllDiscussionsServer) mustEmbedUnimplementedGetAllDiscussionsServer() {}
func (UnimplementedGetAllDiscussionsServer) testEmbeddedByValue()                           {}

// UnsafeGetAllDiscussionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetAllDiscussionsServer will
// result in compilation errors.
type UnsafeGetAllDiscussionsServer interface {
	mustEmbedUnimplementedGetAllDiscussionsServer()
}

func RegisterGetAllDiscussionsServer(s grpc.ServiceRegistrar, srv GetAllDiscussionsServer) {
	// If the following call pancis, it indicates UnimplementedGetAllDiscussionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetAllDiscussions_ServiceDesc, srv)
}

func _GetAllDiscussions_GetAllDiscussions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDiscussionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAllDiscussionsServer).GetAllDiscussions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetAllDiscussions_GetAllDiscussions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAllDiscussionsServer).GetAllDiscussions(ctx, req.(*GetAllDiscussionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetAllDiscussions_ServiceDesc is the grpc.ServiceDesc for GetAllDiscussions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetAllDiscussions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discussions.GetAllDiscussions",
	HandlerType: (*GetAllDiscussionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllDiscussions",
			Handler:    _GetAllDiscussions_GetAllDiscussions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discussions/get_all_discussions.proto",
}
