// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: proto/discussions/get_all_discussions.proto

package discussions_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllDiscussionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetAllDiscussionsRequest) Reset() {
	*x = GetAllDiscussionsRequest{}
	mi := &file_proto_discussions_get_all_discussions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDiscussionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDiscussionsRequest) ProtoMessage() {}

func (x *GetAllDiscussionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discussions_get_all_discussions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDiscussionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllDiscussionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_discussions_get_all_discussions_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllDiscussionsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllDiscussionsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllDiscussionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The GetAll of retrieved Discussions.
	Discussions []*Discussion `protobuf:"bytes,1,rep,name=Discussions,proto3" json:"Discussions,omitempty"`
}

func (x *GetAllDiscussionsResponse) Reset() {
	*x = GetAllDiscussionsResponse{}
	mi := &file_proto_discussions_get_all_discussions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDiscussionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDiscussionsResponse) ProtoMessage() {}

func (x *GetAllDiscussionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discussions_get_all_discussions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDiscussionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllDiscussionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_discussions_get_all_discussions_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllDiscussionsResponse) GetDiscussions() []*Discussion {
	if x != nil {
		return x.Discussions
	}
	return nil
}

var File_proto_discussions_get_all_discussions_proto protoreflect.FileDescriptor

var file_proto_discussions_get_all_discussions_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x69, 0x73, 0x63,
	0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64,
	0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0x56, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69,
	0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x79, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x64, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x75,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x75,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x3b,
	0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_discussions_get_all_discussions_proto_rawDescOnce sync.Once
	file_proto_discussions_get_all_discussions_proto_rawDescData = file_proto_discussions_get_all_discussions_proto_rawDesc
)

func file_proto_discussions_get_all_discussions_proto_rawDescGZIP() []byte {
	file_proto_discussions_get_all_discussions_proto_rawDescOnce.Do(func() {
		file_proto_discussions_get_all_discussions_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_discussions_get_all_discussions_proto_rawDescData)
	})
	return file_proto_discussions_get_all_discussions_proto_rawDescData
}

var file_proto_discussions_get_all_discussions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_discussions_get_all_discussions_proto_goTypes = []any{
	(*GetAllDiscussionsRequest)(nil),  // 0: discussions.GetAllDiscussionsRequest
	(*GetAllDiscussionsResponse)(nil), // 1: discussions.GetAllDiscussionsResponse
	(*Discussion)(nil),                // 2: discussions.Discussion
}
var file_proto_discussions_get_all_discussions_proto_depIdxs = []int32{
	2, // 0: discussions.GetAllDiscussionsResponse.Discussions:type_name -> discussions.Discussion
	0, // 1: discussions.GetAllDiscussions.GetAllDiscussions:input_type -> discussions.GetAllDiscussionsRequest
	1, // 2: discussions.GetAllDiscussions.GetAllDiscussions:output_type -> discussions.GetAllDiscussionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_discussions_get_all_discussions_proto_init() }
func file_proto_discussions_get_all_discussions_proto_init() {
	if File_proto_discussions_get_all_discussions_proto != nil {
		return
	}
	file_proto_discussions_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_discussions_get_all_discussions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_discussions_get_all_discussions_proto_goTypes,
		DependencyIndexes: file_proto_discussions_get_all_discussions_proto_depIdxs,
		MessageInfos:      file_proto_discussions_get_all_discussions_proto_msgTypes,
	}.Build()
	File_proto_discussions_get_all_discussions_proto = out.File
	file_proto_discussions_get_all_discussions_proto_rawDesc = nil
	file_proto_discussions_get_all_discussions_proto_goTypes = nil
	file_proto_discussions_get_all_discussions_proto_depIdxs = nil
}
