// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/discussions/has_unread_discussion.proto

package discussions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HasUnreadDiscussions_HasUnreadDiscussions_FullMethodName = "/discussions.HasUnreadDiscussions/HasUnreadDiscussions"
)

// HasUnreadDiscussionsClient is the client API for HasUnreadDiscussions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasUnreadDiscussionsClient interface {
	// Gets a message in a discussion.
	HasUnreadDiscussions(ctx context.Context, in *HasUnreadDiscussionsRequest, opts ...grpc.CallOption) (*HasUnreadDiscussionsResponse, error)
}

type hasUnreadDiscussionsClient struct {
	cc grpc.ClientConnInterface
}

func NewHasUnreadDiscussionsClient(cc grpc.ClientConnInterface) HasUnreadDiscussionsClient {
	return &hasUnreadDiscussionsClient{cc}
}

func (c *hasUnreadDiscussionsClient) HasUnreadDiscussions(ctx context.Context, in *HasUnreadDiscussionsRequest, opts ...grpc.CallOption) (*HasUnreadDiscussionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasUnreadDiscussionsResponse)
	err := c.cc.Invoke(ctx, HasUnreadDiscussions_HasUnreadDiscussions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HasUnreadDiscussionsServer is the server API for HasUnreadDiscussions service.
// All implementations must embed UnimplementedHasUnreadDiscussionsServer
// for forward compatibility.
type HasUnreadDiscussionsServer interface {
	// Gets a message in a discussion.
	HasUnreadDiscussions(context.Context, *HasUnreadDiscussionsRequest) (*HasUnreadDiscussionsResponse, error)
	mustEmbedUnimplementedHasUnreadDiscussionsServer()
}

// UnimplementedHasUnreadDiscussionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHasUnreadDiscussionsServer struct{}

func (UnimplementedHasUnreadDiscussionsServer) HasUnreadDiscussions(context.Context, *HasUnreadDiscussionsRequest) (*HasUnreadDiscussionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasUnreadDiscussions not implemented")
}
func (UnimplementedHasUnreadDiscussionsServer) mustEmbedUnimplementedHasUnreadDiscussionsServer() {}
func (UnimplementedHasUnreadDiscussionsServer) testEmbeddedByValue()                              {}

// UnsafeHasUnreadDiscussionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasUnreadDiscussionsServer will
// result in compilation errors.
type UnsafeHasUnreadDiscussionsServer interface {
	mustEmbedUnimplementedHasUnreadDiscussionsServer()
}

func RegisterHasUnreadDiscussionsServer(s grpc.ServiceRegistrar, srv HasUnreadDiscussionsServer) {
	// If the following call pancis, it indicates UnimplementedHasUnreadDiscussionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HasUnreadDiscussions_ServiceDesc, srv)
}

func _HasUnreadDiscussions_HasUnreadDiscussions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasUnreadDiscussionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasUnreadDiscussionsServer).HasUnreadDiscussions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HasUnreadDiscussions_HasUnreadDiscussions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasUnreadDiscussionsServer).HasUnreadDiscussions(ctx, req.(*HasUnreadDiscussionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HasUnreadDiscussions_ServiceDesc is the grpc.ServiceDesc for HasUnreadDiscussions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HasUnreadDiscussions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discussions.HasUnreadDiscussions",
	HandlerType: (*HasUnreadDiscussionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasUnreadDiscussions",
			Handler:    _HasUnreadDiscussions_HasUnreadDiscussions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discussions/has_unread_discussion.proto",
}
