// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/discussions/list_discussions_by_team.proto

package discussions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListDiscussionsByTeam_ListDiscussionsByTeam_FullMethodName = "/discussions.ListDiscussionsByTeam/ListDiscussionsByTeam"
)

// ListDiscussionsByTeamClient is the client API for ListDiscussionsByTeam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListDiscussionsByTeamClient interface {
	// Retrieves a discussion.
	ListDiscussionsByTeam(ctx context.Context, in *ListDiscussionsByTeamRequest, opts ...grpc.CallOption) (*ListDiscussionsByTeamResponse, error)
}

type listDiscussionsByTeamClient struct {
	cc grpc.ClientConnInterface
}

func NewListDiscussionsByTeamClient(cc grpc.ClientConnInterface) ListDiscussionsByTeamClient {
	return &listDiscussionsByTeamClient{cc}
}

func (c *listDiscussionsByTeamClient) ListDiscussionsByTeam(ctx context.Context, in *ListDiscussionsByTeamRequest, opts ...grpc.CallOption) (*ListDiscussionsByTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiscussionsByTeamResponse)
	err := c.cc.Invoke(ctx, ListDiscussionsByTeam_ListDiscussionsByTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListDiscussionsByTeamServer is the server API for ListDiscussionsByTeam service.
// All implementations must embed UnimplementedListDiscussionsByTeamServer
// for forward compatibility.
type ListDiscussionsByTeamServer interface {
	// Retrieves a discussion.
	ListDiscussionsByTeam(context.Context, *ListDiscussionsByTeamRequest) (*ListDiscussionsByTeamResponse, error)
	mustEmbedUnimplementedListDiscussionsByTeamServer()
}

// UnimplementedListDiscussionsByTeamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListDiscussionsByTeamServer struct{}

func (UnimplementedListDiscussionsByTeamServer) ListDiscussionsByTeam(context.Context, *ListDiscussionsByTeamRequest) (*ListDiscussionsByTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDiscussionsByTeam not implemented")
}
func (UnimplementedListDiscussionsByTeamServer) mustEmbedUnimplementedListDiscussionsByTeamServer() {}
func (UnimplementedListDiscussionsByTeamServer) testEmbeddedByValue()                               {}

// UnsafeListDiscussionsByTeamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListDiscussionsByTeamServer will
// result in compilation errors.
type UnsafeListDiscussionsByTeamServer interface {
	mustEmbedUnimplementedListDiscussionsByTeamServer()
}

func RegisterListDiscussionsByTeamServer(s grpc.ServiceRegistrar, srv ListDiscussionsByTeamServer) {
	// If the following call pancis, it indicates UnimplementedListDiscussionsByTeamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListDiscussionsByTeam_ServiceDesc, srv)
}

func _ListDiscussionsByTeam_ListDiscussionsByTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiscussionsByTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListDiscussionsByTeamServer).ListDiscussionsByTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListDiscussionsByTeam_ListDiscussionsByTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListDiscussionsByTeamServer).ListDiscussionsByTeam(ctx, req.(*ListDiscussionsByTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListDiscussionsByTeam_ServiceDesc is the grpc.ServiceDesc for ListDiscussionsByTeam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListDiscussionsByTeam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discussions.ListDiscussionsByTeam",
	HandlerType: (*ListDiscussionsByTeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDiscussionsByTeam",
			Handler:    _ListDiscussionsByTeam_ListDiscussionsByTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discussions/list_discussions_by_team.proto",
}
