// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/discussions/update_discussion_read_status.proto

package discussions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateDiscussionReadStatus_UpdateDiscussionReadStatus_FullMethodName = "/discussions.UpdateDiscussionReadStatus/UpdateDiscussionReadStatus"
)

// UpdateDiscussionReadStatusClient is the client API for UpdateDiscussionReadStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateDiscussionReadStatusClient interface {
	// Updates a message in a discussion.
	UpdateDiscussionReadStatus(ctx context.Context, in *UpdateDiscussionReadStatusRequest, opts ...grpc.CallOption) (*DiscussionReadStatus, error)
}

type updateDiscussionReadStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateDiscussionReadStatusClient(cc grpc.ClientConnInterface) UpdateDiscussionReadStatusClient {
	return &updateDiscussionReadStatusClient{cc}
}

func (c *updateDiscussionReadStatusClient) UpdateDiscussionReadStatus(ctx context.Context, in *UpdateDiscussionReadStatusRequest, opts ...grpc.CallOption) (*DiscussionReadStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussionReadStatus)
	err := c.cc.Invoke(ctx, UpdateDiscussionReadStatus_UpdateDiscussionReadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateDiscussionReadStatusServer is the server API for UpdateDiscussionReadStatus service.
// All implementations must embed UnimplementedUpdateDiscussionReadStatusServer
// for forward compatibility.
type UpdateDiscussionReadStatusServer interface {
	// Updates a message in a discussion.
	UpdateDiscussionReadStatus(context.Context, *UpdateDiscussionReadStatusRequest) (*DiscussionReadStatus, error)
	mustEmbedUnimplementedUpdateDiscussionReadStatusServer()
}

// UnimplementedUpdateDiscussionReadStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateDiscussionReadStatusServer struct{}

func (UnimplementedUpdateDiscussionReadStatusServer) UpdateDiscussionReadStatus(context.Context, *UpdateDiscussionReadStatusRequest) (*DiscussionReadStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDiscussionReadStatus not implemented")
}
func (UnimplementedUpdateDiscussionReadStatusServer) mustEmbedUnimplementedUpdateDiscussionReadStatusServer() {
}
func (UnimplementedUpdateDiscussionReadStatusServer) testEmbeddedByValue() {}

// UnsafeUpdateDiscussionReadStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateDiscussionReadStatusServer will
// result in compilation errors.
type UnsafeUpdateDiscussionReadStatusServer interface {
	mustEmbedUnimplementedUpdateDiscussionReadStatusServer()
}

func RegisterUpdateDiscussionReadStatusServer(s grpc.ServiceRegistrar, srv UpdateDiscussionReadStatusServer) {
	// If the following call pancis, it indicates UnimplementedUpdateDiscussionReadStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateDiscussionReadStatus_ServiceDesc, srv)
}

func _UpdateDiscussionReadStatus_UpdateDiscussionReadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiscussionReadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateDiscussionReadStatusServer).UpdateDiscussionReadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateDiscussionReadStatus_UpdateDiscussionReadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateDiscussionReadStatusServer).UpdateDiscussionReadStatus(ctx, req.(*UpdateDiscussionReadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateDiscussionReadStatus_ServiceDesc is the grpc.ServiceDesc for UpdateDiscussionReadStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateDiscussionReadStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discussions.UpdateDiscussionReadStatus",
	HandlerType: (*UpdateDiscussionReadStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDiscussionReadStatus",
			Handler:    _UpdateDiscussionReadStatus_UpdateDiscussionReadStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discussions/update_discussion_read_status.proto",
}
