// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/teams/create_invitation_code.proto

package teams_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateInvitationCode_CreateInvitationCode_FullMethodName = "/CreateInvitationCode/CreateInvitationCode"
)

// CreateInvitationCodeClient is the client API for CreateInvitationCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateInvitationCodeClient interface {
	CreateInvitationCode(ctx context.Context, in *CreateInvitationCodeRequest, opts ...grpc.CallOption) (*CreateInvitationCodeResponse, error)
}

type createInvitationCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateInvitationCodeClient(cc grpc.ClientConnInterface) CreateInvitationCodeClient {
	return &createInvitationCodeClient{cc}
}

func (c *createInvitationCodeClient) CreateInvitationCode(ctx context.Context, in *CreateInvitationCodeRequest, opts ...grpc.CallOption) (*CreateInvitationCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvitationCodeResponse)
	err := c.cc.Invoke(ctx, CreateInvitationCode_CreateInvitationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateInvitationCodeServer is the server API for CreateInvitationCode service.
// All implementations must embed UnimplementedCreateInvitationCodeServer
// for forward compatibility.
type CreateInvitationCodeServer interface {
	CreateInvitationCode(context.Context, *CreateInvitationCodeRequest) (*CreateInvitationCodeResponse, error)
	mustEmbedUnimplementedCreateInvitationCodeServer()
}

// UnimplementedCreateInvitationCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateInvitationCodeServer struct{}

func (UnimplementedCreateInvitationCodeServer) CreateInvitationCode(context.Context, *CreateInvitationCodeRequest) (*CreateInvitationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvitationCode not implemented")
}
func (UnimplementedCreateInvitationCodeServer) mustEmbedUnimplementedCreateInvitationCodeServer() {}
func (UnimplementedCreateInvitationCodeServer) testEmbeddedByValue()                              {}

// UnsafeCreateInvitationCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateInvitationCodeServer will
// result in compilation errors.
type UnsafeCreateInvitationCodeServer interface {
	mustEmbedUnimplementedCreateInvitationCodeServer()
}

func RegisterCreateInvitationCodeServer(s grpc.ServiceRegistrar, srv CreateInvitationCodeServer) {
	// If the following call pancis, it indicates UnimplementedCreateInvitationCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateInvitationCode_ServiceDesc, srv)
}

func _CreateInvitationCode_CreateInvitationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvitationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateInvitationCodeServer).CreateInvitationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateInvitationCode_CreateInvitationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateInvitationCodeServer).CreateInvitationCode(ctx, req.(*CreateInvitationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateInvitationCode_ServiceDesc is the grpc.ServiceDesc for CreateInvitationCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateInvitationCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CreateInvitationCode",
	HandlerType: (*CreateInvitationCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInvitationCode",
			Handler:    _CreateInvitationCode_CreateInvitationCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teams/create_invitation_code.proto",
}
