// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: proto/teams/create_team_member.proto

package teams_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CreateTeamMember_CreateTeamMember_FullMethodName = "/teams.CreateTeamMember/CreateTeamMember"
)

// CreateTeamMemberClient is the client API for CreateTeamMember service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateTeamMemberClient interface {
	// Creates a member of a team.
	CreateTeamMember(ctx context.Context, in *CreateTeamMemberRequest, opts ...grpc.CallOption) (*TeamMember, error)
}

type createTeamMemberClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateTeamMemberClient(cc grpc.ClientConnInterface) CreateTeamMemberClient {
	return &createTeamMemberClient{cc}
}

func (c *createTeamMemberClient) CreateTeamMember(ctx context.Context, in *CreateTeamMemberRequest, opts ...grpc.CallOption) (*TeamMember, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeamMember)
	err := c.cc.Invoke(ctx, CreateTeamMember_CreateTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateTeamMemberServer is the server API for CreateTeamMember service.
// All implementations must embed UnimplementedCreateTeamMemberServer
// for forward compatibility
type CreateTeamMemberServer interface {
	// Creates a member of a team.
	CreateTeamMember(context.Context, *CreateTeamMemberRequest) (*TeamMember, error)
	mustEmbedUnimplementedCreateTeamMemberServer()
}

// UnimplementedCreateTeamMemberServer must be embedded to have forward compatible implementations.
type UnimplementedCreateTeamMemberServer struct {
}

func (UnimplementedCreateTeamMemberServer) CreateTeamMember(context.Context, *CreateTeamMemberRequest) (*TeamMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeamMember not implemented")
}
func (UnimplementedCreateTeamMemberServer) mustEmbedUnimplementedCreateTeamMemberServer() {}

// UnsafeCreateTeamMemberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateTeamMemberServer will
// result in compilation errors.
type UnsafeCreateTeamMemberServer interface {
	mustEmbedUnimplementedCreateTeamMemberServer()
}

func RegisterCreateTeamMemberServer(s grpc.ServiceRegistrar, srv CreateTeamMemberServer) {
	s.RegisterService(&CreateTeamMember_ServiceDesc, srv)
}

func _CreateTeamMember_CreateTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateTeamMemberServer).CreateTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateTeamMember_CreateTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateTeamMemberServer).CreateTeamMember(ctx, req.(*CreateTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateTeamMember_ServiceDesc is the grpc.ServiceDesc for CreateTeamMember service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateTeamMember_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teams.CreateTeamMember",
	HandlerType: (*CreateTeamMemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeamMember",
			Handler:    _CreateTeamMember_CreateTeamMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teams/create_team_member.proto",
}
