// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/teams/create_team.proto

package teams_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateTeam_CreateTeam_FullMethodName = "/teams.CreateTeam/CreateTeam"
)

// CreateTeamClient is the client API for CreateTeam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateTeamClient interface {
	// Creates a new team.
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*Team, error)
}

type createTeamClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateTeamClient(cc grpc.ClientConnInterface) CreateTeamClient {
	return &createTeamClient{cc}
}

func (c *createTeamClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*Team, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Team)
	err := c.cc.Invoke(ctx, CreateTeam_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateTeamServer is the server API for CreateTeam service.
// All implementations must embed UnimplementedCreateTeamServer
// for forward compatibility.
type CreateTeamServer interface {
	// Creates a new team.
	CreateTeam(context.Context, *CreateTeamRequest) (*Team, error)
	mustEmbedUnimplementedCreateTeamServer()
}

// UnimplementedCreateTeamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateTeamServer struct{}

func (UnimplementedCreateTeamServer) CreateTeam(context.Context, *CreateTeamRequest) (*Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedCreateTeamServer) mustEmbedUnimplementedCreateTeamServer() {}
func (UnimplementedCreateTeamServer) testEmbeddedByValue()                    {}

// UnsafeCreateTeamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateTeamServer will
// result in compilation errors.
type UnsafeCreateTeamServer interface {
	mustEmbedUnimplementedCreateTeamServer()
}

func RegisterCreateTeamServer(s grpc.ServiceRegistrar, srv CreateTeamServer) {
	// If the following call pancis, it indicates UnimplementedCreateTeamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateTeam_ServiceDesc, srv)
}

func _CreateTeam_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateTeamServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateTeam_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateTeamServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateTeam_ServiceDesc is the grpc.ServiceDesc for CreateTeam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateTeam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teams.CreateTeam",
	HandlerType: (*CreateTeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeam",
			Handler:    _CreateTeam_CreateTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teams/create_team.proto",
}
