// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.4
// source: proto/teams/join_team_with_invitation.proto

package teams_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JoinTeamWIthInvitation_JoinTeamWIthInvitation_FullMethodName = "/JoinTeamWIthInvitation/JoinTeamWIthInvitation"
)

// JoinTeamWIthInvitationClient is the client API for JoinTeamWIthInvitation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoinTeamWIthInvitationClient interface {
	JoinTeamWIthInvitation(ctx context.Context, in *JoinTeamWIthInvitationRequest, opts ...grpc.CallOption) (*JoinTeamWIthInvitationResponse, error)
}

type joinTeamWIthInvitationClient struct {
	cc grpc.ClientConnInterface
}

func NewJoinTeamWIthInvitationClient(cc grpc.ClientConnInterface) JoinTeamWIthInvitationClient {
	return &joinTeamWIthInvitationClient{cc}
}

func (c *joinTeamWIthInvitationClient) JoinTeamWIthInvitation(ctx context.Context, in *JoinTeamWIthInvitationRequest, opts ...grpc.CallOption) (*JoinTeamWIthInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinTeamWIthInvitationResponse)
	err := c.cc.Invoke(ctx, JoinTeamWIthInvitation_JoinTeamWIthInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoinTeamWIthInvitationServer is the server API for JoinTeamWIthInvitation service.
// All implementations must embed UnimplementedJoinTeamWIthInvitationServer
// for forward compatibility.
type JoinTeamWIthInvitationServer interface {
	JoinTeamWIthInvitation(context.Context, *JoinTeamWIthInvitationRequest) (*JoinTeamWIthInvitationResponse, error)
	mustEmbedUnimplementedJoinTeamWIthInvitationServer()
}

// UnimplementedJoinTeamWIthInvitationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoinTeamWIthInvitationServer struct{}

func (UnimplementedJoinTeamWIthInvitationServer) JoinTeamWIthInvitation(context.Context, *JoinTeamWIthInvitationRequest) (*JoinTeamWIthInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinTeamWIthInvitation not implemented")
}
func (UnimplementedJoinTeamWIthInvitationServer) mustEmbedUnimplementedJoinTeamWIthInvitationServer() {
}
func (UnimplementedJoinTeamWIthInvitationServer) testEmbeddedByValue() {}

// UnsafeJoinTeamWIthInvitationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoinTeamWIthInvitationServer will
// result in compilation errors.
type UnsafeJoinTeamWIthInvitationServer interface {
	mustEmbedUnimplementedJoinTeamWIthInvitationServer()
}

func RegisterJoinTeamWIthInvitationServer(s grpc.ServiceRegistrar, srv JoinTeamWIthInvitationServer) {
	// If the following call pancis, it indicates UnimplementedJoinTeamWIthInvitationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoinTeamWIthInvitation_ServiceDesc, srv)
}

func _JoinTeamWIthInvitation_JoinTeamWIthInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTeamWIthInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinTeamWIthInvitationServer).JoinTeamWIthInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinTeamWIthInvitation_JoinTeamWIthInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinTeamWIthInvitationServer).JoinTeamWIthInvitation(ctx, req.(*JoinTeamWIthInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoinTeamWIthInvitation_ServiceDesc is the grpc.ServiceDesc for JoinTeamWIthInvitation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoinTeamWIthInvitation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JoinTeamWIthInvitation",
	HandlerType: (*JoinTeamWIthInvitationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinTeamWIthInvitation",
			Handler:    _JoinTeamWIthInvitation_JoinTeamWIthInvitation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teams/join_team_with_invitation.proto",
}
