// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.4
// source: proto/teams/update_team.proto

package teams_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateTeam_UpdateTeam_FullMethodName = "/teams.UpdateTeam/UpdateTeam"
)

// UpdateTeamClient is the client API for UpdateTeam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateTeamClient interface {
	// Updates a team.
	UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*Team, error)
}

type updateTeamClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateTeamClient(cc grpc.ClientConnInterface) UpdateTeamClient {
	return &updateTeamClient{cc}
}

func (c *updateTeamClient) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*Team, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Team)
	err := c.cc.Invoke(ctx, UpdateTeam_UpdateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateTeamServer is the server API for UpdateTeam service.
// All implementations must embed UnimplementedUpdateTeamServer
// for forward compatibility.
type UpdateTeamServer interface {
	// Updates a team.
	UpdateTeam(context.Context, *UpdateTeamRequest) (*Team, error)
	mustEmbedUnimplementedUpdateTeamServer()
}

// UnimplementedUpdateTeamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateTeamServer struct{}

func (UnimplementedUpdateTeamServer) UpdateTeam(context.Context, *UpdateTeamRequest) (*Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (UnimplementedUpdateTeamServer) mustEmbedUnimplementedUpdateTeamServer() {}
func (UnimplementedUpdateTeamServer) testEmbeddedByValue()                    {}

// UnsafeUpdateTeamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateTeamServer will
// result in compilation errors.
type UnsafeUpdateTeamServer interface {
	mustEmbedUnimplementedUpdateTeamServer()
}

func RegisterUpdateTeamServer(s grpc.ServiceRegistrar, srv UpdateTeamServer) {
	// If the following call pancis, it indicates UnimplementedUpdateTeamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateTeam_ServiceDesc, srv)
}

func _UpdateTeam_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateTeamServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateTeam_UpdateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateTeamServer).UpdateTeam(ctx, req.(*UpdateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateTeam_ServiceDesc is the grpc.ServiceDesc for UpdateTeam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateTeam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teams.UpdateTeam",
	HandlerType: (*UpdateTeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTeam",
			Handler:    _UpdateTeam_UpdateTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teams/update_team.proto",
}
