// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/notes/get_note.proto

package notes_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetNote_GetNote_FullMethodName = "/notes.GetNote/GetNote"
)

// GetNoteClient is the client API for GetNote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetNoteClient interface {
	// Retrieves a note.
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*Note, error)
}

type getNoteClient struct {
	cc grpc.ClientConnInterface
}

func NewGetNoteClient(cc grpc.ClientConnInterface) GetNoteClient {
	return &getNoteClient{cc}
}

func (c *getNoteClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, GetNote_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetNoteServer is the server API for GetNote service.
// All implementations must embed UnimplementedGetNoteServer
// for forward compatibility.
type GetNoteServer interface {
	// Retrieves a note.
	GetNote(context.Context, *GetNoteRequest) (*Note, error)
	mustEmbedUnimplementedGetNoteServer()
}

// UnimplementedGetNoteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetNoteServer struct{}

func (UnimplementedGetNoteServer) GetNote(context.Context, *GetNoteRequest) (*Note, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedGetNoteServer) mustEmbedUnimplementedGetNoteServer() {}
func (UnimplementedGetNoteServer) testEmbeddedByValue()                 {}

// UnsafeGetNoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetNoteServer will
// result in compilation errors.
type UnsafeGetNoteServer interface {
	mustEmbedUnimplementedGetNoteServer()
}

func RegisterGetNoteServer(s grpc.ServiceRegistrar, srv GetNoteServer) {
	// If the following call pancis, it indicates UnimplementedGetNoteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetNote_ServiceDesc, srv)
}

func _GetNote_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetNoteServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetNote_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetNoteServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetNote_ServiceDesc is the grpc.ServiceDesc for GetNote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetNote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.GetNote",
	HandlerType: (*GetNoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _GetNote_GetNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notes/get_note.proto",
}
