// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/notes/get_all_notes.proto

package notes_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetAllNotes_GetAllNotes_FullMethodName = "/notes.GetAllNotes/GetAllNotes"
)

// GetAllNotesClient is the client API for GetAllNotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetAllNotesClient interface {
	// Retrieves a note.
	GetAllNotes(ctx context.Context, in *GetAllNotesRequest, opts ...grpc.CallOption) (*GetAllNotesResponse, error)
}

type getAllNotesClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAllNotesClient(cc grpc.ClientConnInterface) GetAllNotesClient {
	return &getAllNotesClient{cc}
}

func (c *getAllNotesClient) GetAllNotes(ctx context.Context, in *GetAllNotesRequest, opts ...grpc.CallOption) (*GetAllNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllNotesResponse)
	err := c.cc.Invoke(ctx, GetAllNotes_GetAllNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAllNotesServer is the server API for GetAllNotes service.
// All implementations must embed UnimplementedGetAllNotesServer
// for forward compatibility.
type GetAllNotesServer interface {
	// Retrieves a note.
	GetAllNotes(context.Context, *GetAllNotesRequest) (*GetAllNotesResponse, error)
	mustEmbedUnimplementedGetAllNotesServer()
}

// UnimplementedGetAllNotesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetAllNotesServer struct{}

func (UnimplementedGetAllNotesServer) GetAllNotes(context.Context, *GetAllNotesRequest) (*GetAllNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllNotes not implemented")
}
func (UnimplementedGetAllNotesServer) mustEmbedUnimplementedGetAllNotesServer() {}
func (UnimplementedGetAllNotesServer) testEmbeddedByValue()                     {}

// UnsafeGetAllNotesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetAllNotesServer will
// result in compilation errors.
type UnsafeGetAllNotesServer interface {
	mustEmbedUnimplementedGetAllNotesServer()
}

func RegisterGetAllNotesServer(s grpc.ServiceRegistrar, srv GetAllNotesServer) {
	// If the following call pancis, it indicates UnimplementedGetAllNotesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetAllNotes_ServiceDesc, srv)
}

func _GetAllNotes_GetAllNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAllNotesServer).GetAllNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetAllNotes_GetAllNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAllNotesServer).GetAllNotes(ctx, req.(*GetAllNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetAllNotes_ServiceDesc is the grpc.ServiceDesc for GetAllNotes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetAllNotes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.GetAllNotes",
	HandlerType: (*GetAllNotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllNotes",
			Handler:    _GetAllNotes_GetAllNotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notes/get_all_notes.proto",
}
