// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: proto/notes/list_notes.proto

package notes_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ListNotes_ListNotes_FullMethodName = "/notes.ListNotes/ListNotes"
)

// ListNotesClient is the client API for ListNotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListNotesClient interface {
	// Retrieves a note.
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
}

type listNotesClient struct {
	cc grpc.ClientConnInterface
}

func NewListNotesClient(cc grpc.ClientConnInterface) ListNotesClient {
	return &listNotesClient{cc}
}

func (c *listNotesClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, ListNotes_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListNotesServer is the server API for ListNotes service.
// All implementations must embed UnimplementedListNotesServer
// for forward compatibility
type ListNotesServer interface {
	// Retrieves a note.
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	mustEmbedUnimplementedListNotesServer()
}

// UnimplementedListNotesServer must be embedded to have forward compatible implementations.
type UnimplementedListNotesServer struct {
}

func (UnimplementedListNotesServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedListNotesServer) mustEmbedUnimplementedListNotesServer() {}

// UnsafeListNotesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListNotesServer will
// result in compilation errors.
type UnsafeListNotesServer interface {
	mustEmbedUnimplementedListNotesServer()
}

func RegisterListNotesServer(s grpc.ServiceRegistrar, srv ListNotesServer) {
	s.RegisterService(&ListNotes_ServiceDesc, srv)
}

func _ListNotes_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListNotesServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListNotes_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListNotesServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListNotes_ServiceDesc is the grpc.ServiceDesc for ListNotes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListNotes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.ListNotes",
	HandlerType: (*ListNotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNotes",
			Handler:    _ListNotes_ListNotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notes/list_notes.proto",
}
