// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/notes/upsert_note.proto

package notes_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpsertNote_UpsertNote_FullMethodName = "/notes.UpsertNote/UpsertNote"
)

// UpsertNoteClient is the client API for UpsertNote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpsertNoteClient interface {
	// Upsert a note.
	UpsertNote(ctx context.Context, in *UpsertNoteRequest, opts ...grpc.CallOption) (*UpsertNoteResponse, error)
}

type upsertNoteClient struct {
	cc grpc.ClientConnInterface
}

func NewUpsertNoteClient(cc grpc.ClientConnInterface) UpsertNoteClient {
	return &upsertNoteClient{cc}
}

func (c *upsertNoteClient) UpsertNote(ctx context.Context, in *UpsertNoteRequest, opts ...grpc.CallOption) (*UpsertNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertNoteResponse)
	err := c.cc.Invoke(ctx, UpsertNote_UpsertNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpsertNoteServer is the server API for UpsertNote service.
// All implementations must embed UnimplementedUpsertNoteServer
// for forward compatibility.
type UpsertNoteServer interface {
	// Upsert a note.
	UpsertNote(context.Context, *UpsertNoteRequest) (*UpsertNoteResponse, error)
	mustEmbedUnimplementedUpsertNoteServer()
}

// UnimplementedUpsertNoteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpsertNoteServer struct{}

func (UnimplementedUpsertNoteServer) UpsertNote(context.Context, *UpsertNoteRequest) (*UpsertNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertNote not implemented")
}
func (UnimplementedUpsertNoteServer) mustEmbedUnimplementedUpsertNoteServer() {}
func (UnimplementedUpsertNoteServer) testEmbeddedByValue()                    {}

// UnsafeUpsertNoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpsertNoteServer will
// result in compilation errors.
type UnsafeUpsertNoteServer interface {
	mustEmbedUnimplementedUpsertNoteServer()
}

func RegisterUpsertNoteServer(s grpc.ServiceRegistrar, srv UpsertNoteServer) {
	// If the following call pancis, it indicates UnimplementedUpsertNoteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpsertNote_ServiceDesc, srv)
}

func _UpsertNote_UpsertNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsertNoteServer).UpsertNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsertNote_UpsertNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsertNoteServer).UpsertNote(ctx, req.(*UpsertNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpsertNote_ServiceDesc is the grpc.ServiceDesc for UpsertNote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpsertNote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.UpsertNote",
	HandlerType: (*UpsertNoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertNote",
			Handler:    _UpsertNote_UpsertNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notes/upsert_note.proto",
}
