// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/linkedin-data/get_company_last_update.proto

package linkedin_data_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCompanyLastUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The vanity name of the company, as it appears in its LinkedIn profile URL.
	PublicIdentifier string `protobuf:"bytes,1,opt,name=public_identifier,json=publicIdentifier,proto3" json:"public_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCompanyLastUpdateRequest) Reset() {
	*x = GetCompanyLastUpdateRequest{}
	mi := &file_proto_linkedin_data_get_company_last_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyLastUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyLastUpdateRequest) ProtoMessage() {}

func (x *GetCompanyLastUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linkedin_data_get_company_last_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyLastUpdateRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyLastUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_linkedin_data_get_company_last_update_proto_rawDescGZIP(), []int{0}
}

func (x *GetCompanyLastUpdateRequest) GetPublicIdentifier() string {
	if x != nil {
		return x.PublicIdentifier
	}
	return ""
}

type GetCompanyLastUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp of the company information latest update.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyLastUpdateResponse) Reset() {
	*x = GetCompanyLastUpdateResponse{}
	mi := &file_proto_linkedin_data_get_company_last_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyLastUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyLastUpdateResponse) ProtoMessage() {}

func (x *GetCompanyLastUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linkedin_data_get_company_last_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyLastUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyLastUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_linkedin_data_get_company_last_update_proto_rawDescGZIP(), []int{1}
}

func (x *GetCompanyLastUpdateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_linkedin_data_get_company_last_update_proto protoreflect.FileDescriptor

var file_proto_linkedin_data_get_company_last_update_proto_rawDesc = string([]byte{
	0x0a, 0x31, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e,
	0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x59,
	0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x87, 0x01, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x6f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x29, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x3b, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_linkedin_data_get_company_last_update_proto_rawDescOnce sync.Once
	file_proto_linkedin_data_get_company_last_update_proto_rawDescData []byte
)

func file_proto_linkedin_data_get_company_last_update_proto_rawDescGZIP() []byte {
	file_proto_linkedin_data_get_company_last_update_proto_rawDescOnce.Do(func() {
		file_proto_linkedin_data_get_company_last_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_linkedin_data_get_company_last_update_proto_rawDesc), len(file_proto_linkedin_data_get_company_last_update_proto_rawDesc)))
	})
	return file_proto_linkedin_data_get_company_last_update_proto_rawDescData
}

var file_proto_linkedin_data_get_company_last_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_linkedin_data_get_company_last_update_proto_goTypes = []any{
	(*GetCompanyLastUpdateRequest)(nil),  // 0: linkedinData.GetCompanyLastUpdateRequest
	(*GetCompanyLastUpdateResponse)(nil), // 1: linkedinData.GetCompanyLastUpdateResponse
	(*timestamppb.Timestamp)(nil),        // 2: google.protobuf.Timestamp
}
var file_proto_linkedin_data_get_company_last_update_proto_depIdxs = []int32{
	2, // 0: linkedinData.GetCompanyLastUpdateResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: linkedinData.GetCompanyLastUpdate.GetCompanyLastUpdate:input_type -> linkedinData.GetCompanyLastUpdateRequest
	1, // 2: linkedinData.GetCompanyLastUpdate.GetCompanyLastUpdate:output_type -> linkedinData.GetCompanyLastUpdateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_linkedin_data_get_company_last_update_proto_init() }
func file_proto_linkedin_data_get_company_last_update_proto_init() {
	if File_proto_linkedin_data_get_company_last_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_linkedin_data_get_company_last_update_proto_rawDesc), len(file_proto_linkedin_data_get_company_last_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_linkedin_data_get_company_last_update_proto_goTypes,
		DependencyIndexes: file_proto_linkedin_data_get_company_last_update_proto_depIdxs,
		MessageInfos:      file_proto_linkedin_data_get_company_last_update_proto_msgTypes,
	}.Build()
	File_proto_linkedin_data_get_company_last_update_proto = out.File
	file_proto_linkedin_data_get_company_last_update_proto_goTypes = nil
	file_proto_linkedin_data_get_company_last_update_proto_depIdxs = nil
}
