// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: proto/linkedin-data/get_user_last_update.proto

package linkedin_data_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserLastUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The vanity name of the user, as it appears in its LinkedIn profile URL.
	PublicIdentifier string `protobuf:"bytes,1,opt,name=public_identifier,json=publicIdentifier,proto3" json:"public_identifier,omitempty"`
}

func (x *GetUserLastUpdateRequest) Reset() {
	*x = GetUserLastUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_linkedin_data_get_user_last_update_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLastUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLastUpdateRequest) ProtoMessage() {}

func (x *GetUserLastUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linkedin_data_get_user_last_update_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLastUpdateRequest.ProtoReflect.Descriptor instead.
func (*GetUserLastUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_linkedin_data_get_user_last_update_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserLastUpdateRequest) GetPublicIdentifier() string {
	if x != nil {
		return x.PublicIdentifier
	}
	return ""
}

type GetUserLastUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The timestamp of the user information latest update.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *GetUserLastUpdateResponse) Reset() {
	*x = GetUserLastUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_linkedin_data_get_user_last_update_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLastUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLastUpdateResponse) ProtoMessage() {}

func (x *GetUserLastUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linkedin_data_get_user_last_update_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLastUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetUserLastUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_linkedin_data_get_user_last_update_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserLastUpdateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_linkedin_data_get_user_last_update_proto protoreflect.FileDescriptor

var file_proto_linkedin_data_get_user_last_update_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e,
	0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x47, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x56, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x32, 0x7b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a,
	0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x69, 0x6e, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x3b, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x69, 0x6e,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_linkedin_data_get_user_last_update_proto_rawDescOnce sync.Once
	file_proto_linkedin_data_get_user_last_update_proto_rawDescData = file_proto_linkedin_data_get_user_last_update_proto_rawDesc
)

func file_proto_linkedin_data_get_user_last_update_proto_rawDescGZIP() []byte {
	file_proto_linkedin_data_get_user_last_update_proto_rawDescOnce.Do(func() {
		file_proto_linkedin_data_get_user_last_update_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_linkedin_data_get_user_last_update_proto_rawDescData)
	})
	return file_proto_linkedin_data_get_user_last_update_proto_rawDescData
}

var file_proto_linkedin_data_get_user_last_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_linkedin_data_get_user_last_update_proto_goTypes = []any{
	(*GetUserLastUpdateRequest)(nil),  // 0: linkedinData.GetUserLastUpdateRequest
	(*GetUserLastUpdateResponse)(nil), // 1: linkedinData.GetUserLastUpdateResponse
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_proto_linkedin_data_get_user_last_update_proto_depIdxs = []int32{
	2, // 0: linkedinData.GetUserLastUpdateResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: linkedinData.GetUserLastUpdate.GetUserLastUpdate:input_type -> linkedinData.GetUserLastUpdateRequest
	1, // 2: linkedinData.GetUserLastUpdate.GetUserLastUpdate:output_type -> linkedinData.GetUserLastUpdateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_linkedin_data_get_user_last_update_proto_init() }
func file_proto_linkedin_data_get_user_last_update_proto_init() {
	if File_proto_linkedin_data_get_user_last_update_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_linkedin_data_get_user_last_update_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserLastUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_linkedin_data_get_user_last_update_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserLastUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_linkedin_data_get_user_last_update_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_linkedin_data_get_user_last_update_proto_goTypes,
		DependencyIndexes: file_proto_linkedin_data_get_user_last_update_proto_depIdxs,
		MessageInfos:      file_proto_linkedin_data_get_user_last_update_proto_msgTypes,
	}.Build()
	File_proto_linkedin_data_get_user_last_update_proto = out.File
	file_proto_linkedin_data_get_user_last_update_proto_rawDesc = nil
	file_proto_linkedin_data_get_user_last_update_proto_goTypes = nil
	file_proto_linkedin_data_get_user_last_update_proto_depIdxs = nil
}
