// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/linkedin-data/get_user_last_update.proto

package linkedin_data_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetUserLastUpdate_GetUserLastUpdate_FullMethodName = "/linkedinData.GetUserLastUpdate/GetUserLastUpdate"
)

// GetUserLastUpdateClient is the client API for GetUserLastUpdate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetUserLastUpdateClient interface {
	// Retrieves a user's LinkedIn profile data.
	GetUserLastUpdate(ctx context.Context, in *GetUserLastUpdateRequest, opts ...grpc.CallOption) (*GetUserLastUpdateResponse, error)
}

type getUserLastUpdateClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUserLastUpdateClient(cc grpc.ClientConnInterface) GetUserLastUpdateClient {
	return &getUserLastUpdateClient{cc}
}

func (c *getUserLastUpdateClient) GetUserLastUpdate(ctx context.Context, in *GetUserLastUpdateRequest, opts ...grpc.CallOption) (*GetUserLastUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLastUpdateResponse)
	err := c.cc.Invoke(ctx, GetUserLastUpdate_GetUserLastUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserLastUpdateServer is the server API for GetUserLastUpdate service.
// All implementations must embed UnimplementedGetUserLastUpdateServer
// for forward compatibility.
type GetUserLastUpdateServer interface {
	// Retrieves a user's LinkedIn profile data.
	GetUserLastUpdate(context.Context, *GetUserLastUpdateRequest) (*GetUserLastUpdateResponse, error)
	mustEmbedUnimplementedGetUserLastUpdateServer()
}

// UnimplementedGetUserLastUpdateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetUserLastUpdateServer struct{}

func (UnimplementedGetUserLastUpdateServer) GetUserLastUpdate(context.Context, *GetUserLastUpdateRequest) (*GetUserLastUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLastUpdate not implemented")
}
func (UnimplementedGetUserLastUpdateServer) mustEmbedUnimplementedGetUserLastUpdateServer() {}
func (UnimplementedGetUserLastUpdateServer) testEmbeddedByValue()                           {}

// UnsafeGetUserLastUpdateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetUserLastUpdateServer will
// result in compilation errors.
type UnsafeGetUserLastUpdateServer interface {
	mustEmbedUnimplementedGetUserLastUpdateServer()
}

func RegisterGetUserLastUpdateServer(s grpc.ServiceRegistrar, srv GetUserLastUpdateServer) {
	// If the following call pancis, it indicates UnimplementedGetUserLastUpdateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetUserLastUpdate_ServiceDesc, srv)
}

func _GetUserLastUpdate_GetUserLastUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLastUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserLastUpdateServer).GetUserLastUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetUserLastUpdate_GetUserLastUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserLastUpdateServer).GetUserLastUpdate(ctx, req.(*GetUserLastUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetUserLastUpdate_ServiceDesc is the grpc.ServiceDesc for GetUserLastUpdate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetUserLastUpdate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkedinData.GetUserLastUpdate",
	HandlerType: (*GetUserLastUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserLastUpdate",
			Handler:    _GetUserLastUpdate_GetUserLastUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/linkedin-data/get_user_last_update.proto",
}
