// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/linkedin-data/upsert_company.proto

package linkedin_data_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpsertCompany_UpsertCompany_FullMethodName = "/linkedinData.UpsertCompany/UpsertCompany"
)

// UpsertCompanyClient is the client API for UpsertCompany service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpsertCompanyClient interface {
	// Update the LinkedIn data of a company.
	UpsertCompany(ctx context.Context, in *UpsertCompanyRequest, opts ...grpc.CallOption) (*Company, error)
}

type upsertCompanyClient struct {
	cc grpc.ClientConnInterface
}

func NewUpsertCompanyClient(cc grpc.ClientConnInterface) UpsertCompanyClient {
	return &upsertCompanyClient{cc}
}

func (c *upsertCompanyClient) UpsertCompany(ctx context.Context, in *UpsertCompanyRequest, opts ...grpc.CallOption) (*Company, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Company)
	err := c.cc.Invoke(ctx, UpsertCompany_UpsertCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpsertCompanyServer is the server API for UpsertCompany service.
// All implementations must embed UnimplementedUpsertCompanyServer
// for forward compatibility.
type UpsertCompanyServer interface {
	// Update the LinkedIn data of a company.
	UpsertCompany(context.Context, *UpsertCompanyRequest) (*Company, error)
	mustEmbedUnimplementedUpsertCompanyServer()
}

// UnimplementedUpsertCompanyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpsertCompanyServer struct{}

func (UnimplementedUpsertCompanyServer) UpsertCompany(context.Context, *UpsertCompanyRequest) (*Company, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCompany not implemented")
}
func (UnimplementedUpsertCompanyServer) mustEmbedUnimplementedUpsertCompanyServer() {}
func (UnimplementedUpsertCompanyServer) testEmbeddedByValue()                       {}

// UnsafeUpsertCompanyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpsertCompanyServer will
// result in compilation errors.
type UnsafeUpsertCompanyServer interface {
	mustEmbedUnimplementedUpsertCompanyServer()
}

func RegisterUpsertCompanyServer(s grpc.ServiceRegistrar, srv UpsertCompanyServer) {
	// If the following call pancis, it indicates UnimplementedUpsertCompanyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpsertCompany_ServiceDesc, srv)
}

func _UpsertCompany_UpsertCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsertCompanyServer).UpsertCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsertCompany_UpsertCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsertCompanyServer).UpsertCompany(ctx, req.(*UpsertCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpsertCompany_ServiceDesc is the grpc.ServiceDesc for UpsertCompany service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpsertCompany_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkedinData.UpsertCompany",
	HandlerType: (*UpsertCompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertCompany",
			Handler:    _UpsertCompany_UpsertCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/linkedin-data/upsert_company.proto",
}
