// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: proto/reminders/get_reminder_by_id.proto

package reminders_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReminderByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the reminders to retrieve.
	ReminderId string `protobuf:"bytes,1,opt,name=reminder_id,json=reminderId,proto3" json:"reminder_id,omitempty"`
	// The id of the reminder's author.
	AuthorId string `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *GetReminderByIDRequest) Reset() {
	*x = GetReminderByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reminders_get_reminder_by_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderByIDRequest) ProtoMessage() {}

func (x *GetReminderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reminders_get_reminder_by_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetReminderByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_reminders_get_reminder_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetReminderByIDRequest) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

func (x *GetReminderByIDRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

var File_proto_reminders_get_reminder_by_id_proto protoreflect.FileDescriptor

var file_proto_reminders_get_reminder_by_id_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x62,
	0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x32, 0x5e, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x4b,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49,
	0x44, 0x12, 0x21, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x3b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reminders_get_reminder_by_id_proto_rawDescOnce sync.Once
	file_proto_reminders_get_reminder_by_id_proto_rawDescData = file_proto_reminders_get_reminder_by_id_proto_rawDesc
)

func file_proto_reminders_get_reminder_by_id_proto_rawDescGZIP() []byte {
	file_proto_reminders_get_reminder_by_id_proto_rawDescOnce.Do(func() {
		file_proto_reminders_get_reminder_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reminders_get_reminder_by_id_proto_rawDescData)
	})
	return file_proto_reminders_get_reminder_by_id_proto_rawDescData
}

var file_proto_reminders_get_reminder_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_reminders_get_reminder_by_id_proto_goTypes = []any{
	(*GetReminderByIDRequest)(nil), // 0: reminders.GetReminderByIDRequest
	(*Reminder)(nil),               // 1: reminders.Reminder
}
var file_proto_reminders_get_reminder_by_id_proto_depIdxs = []int32{
	0, // 0: reminders.GetReminderByID.GetReminderByID:input_type -> reminders.GetReminderByIDRequest
	1, // 1: reminders.GetReminderByID.GetReminderByID:output_type -> reminders.Reminder
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reminders_get_reminder_by_id_proto_init() }
func file_proto_reminders_get_reminder_by_id_proto_init() {
	if File_proto_reminders_get_reminder_by_id_proto != nil {
		return
	}
	file_proto_reminders_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_reminders_get_reminder_by_id_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetReminderByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reminders_get_reminder_by_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reminders_get_reminder_by_id_proto_goTypes,
		DependencyIndexes: file_proto_reminders_get_reminder_by_id_proto_depIdxs,
		MessageInfos:      file_proto_reminders_get_reminder_by_id_proto_msgTypes,
	}.Build()
	File_proto_reminders_get_reminder_by_id_proto = out.File
	file_proto_reminders_get_reminder_by_id_proto_rawDesc = nil
	file_proto_reminders_get_reminder_by_id_proto_goTypes = nil
	file_proto_reminders_get_reminder_by_id_proto_depIdxs = nil
}
