// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/reminders/get_reminder.proto

package reminders_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetReminder_GetReminder_FullMethodName = "/reminders.GetReminder/GetReminder"
)

// GetReminderClient is the client API for GetReminder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetReminderClient interface {
	// Retrieves a reminder.
	GetReminder(ctx context.Context, in *GetReminderRequest, opts ...grpc.CallOption) (*Reminder, error)
}

type getReminderClient struct {
	cc grpc.ClientConnInterface
}

func NewGetReminderClient(cc grpc.ClientConnInterface) GetReminderClient {
	return &getReminderClient{cc}
}

func (c *getReminderClient) GetReminder(ctx context.Context, in *GetReminderRequest, opts ...grpc.CallOption) (*Reminder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reminder)
	err := c.cc.Invoke(ctx, GetReminder_GetReminder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetReminderServer is the server API for GetReminder service.
// All implementations must embed UnimplementedGetReminderServer
// for forward compatibility.
type GetReminderServer interface {
	// Retrieves a reminder.
	GetReminder(context.Context, *GetReminderRequest) (*Reminder, error)
	mustEmbedUnimplementedGetReminderServer()
}

// UnimplementedGetReminderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetReminderServer struct{}

func (UnimplementedGetReminderServer) GetReminder(context.Context, *GetReminderRequest) (*Reminder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReminder not implemented")
}
func (UnimplementedGetReminderServer) mustEmbedUnimplementedGetReminderServer() {}
func (UnimplementedGetReminderServer) testEmbeddedByValue()                     {}

// UnsafeGetReminderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetReminderServer will
// result in compilation errors.
type UnsafeGetReminderServer interface {
	mustEmbedUnimplementedGetReminderServer()
}

func RegisterGetReminderServer(s grpc.ServiceRegistrar, srv GetReminderServer) {
	// If the following call pancis, it indicates UnimplementedGetReminderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetReminder_ServiceDesc, srv)
}

func _GetReminder_GetReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetReminderServer).GetReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetReminder_GetReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetReminderServer).GetReminder(ctx, req.(*GetReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetReminder_ServiceDesc is the grpc.ServiceDesc for GetReminder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetReminder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reminders.GetReminder",
	HandlerType: (*GetReminderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReminder",
			Handler:    _GetReminder_GetReminder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reminders/get_reminder.proto",
}
